#!/bin/bash

#
# Entrypoint for the devlab container.
#
# The main purpose for this script is to execute any commands
# before we execute the actual command passed to us.
#
# The script takes one or more parameters, the first of which is
# the command to be executed, and the rest of them are the commands
# for that script.
# 
# Author: arvindd
# Created: 27.Apr.2021
#
# Copyright (c) 2021 Arvind Devarajan
# Licensed to you under the MIT License.
# See the LICENSE file in the project root for more information.
#

set -e

# First, make sure our work directory is writable
mkdir -p work
sudo zsh -c 'chown dev:users work'

# If we have mounted a /opt/certs directory, then, we
# have some certificates to be installed.
# our trust stores.
if [[ -d /opt/certs ]]; then
    sudo zsh -c "cp /opt/certs/* /etc/pki/trust/anchors"
    sudo zsh -c "update-ca-certificates"
fi 

exec "$@"
