#!/bin/zsh
#
# Entrypoint for the devlab container.
#
# The main purpose for this script is to execute any commands
# before we execute the actual command passed to us.
#
# The script takes one or more parameters, the first of which is
# the command to be executed, and the rest of them are the commands
# for that script.
# 
# Copyright (c) 2021 Arvind Devarajan
# Licensed to you under the MIT License.
# See the LICENSE file in the project root for more information.

#
# Make sure that VSCODEENV is set as settings in the VSCODE settings.json:
#   "terminal.integrated.env.linux": {
#         .....
#        "VSCODEENV":"true"
#    }

# Do not start tmux if we are already inside a tmux or in a vscode
if [[ -z "$TMUX" ]]; then
   if [[ $VSCODEENV = "true" ]]; then
      (tmux -2 -u attach -t vscode || tmux -2 -u new -s vscode \; split-window -v \; select-pane -t0) && exit
   else
       (tmux -2 -u attach -t console || tmux -2 -u new -s console \; split-window -h \; split-window -v \; select-pane -t0) && exit
   fi
fi
